// Generated by scripts/post-stories.mjs from content/post-stories/*.json. Edit those, then run it with --write.
import type { PostStory } from "@/components/blog/story/types"

export const POST_STORIES: Record<string, PostStory> = {
    "ai-resume-screening-explained": {
        "slug": "ai-resume-screening-explained",
        "form": "flow",
        "title": "No AI judges your resume; a parser files it and a person searches",
        "takeaway": "The step that costs interviews is the silent parse, so fix what the parser extracts, then stop optimising for the machine.",
        "sources": [
            "There is no AI reading your resume for potential.",
            "This is the step that fails, and it fails silently.",
            "Six to eight seconds per resume, in a list view.",
            "The system parses and indexes; a person decides."
        ],
        "data": {
            "nodes": [
                {
                    "id": "parse",
                    "label": "Parsed into fields",
                    "note": "Two columns and odd headers lose the structure"
                },
                {
                    "id": "index",
                    "label": "Text indexed",
                    "note": "Searchable, keyword by keyword"
                },
                {
                    "id": "search",
                    "label": "Recruiter runs a search",
                    "note": "You appear in the results or you do not"
                },
                {
                    "id": "skim",
                    "label": "A human skims",
                    "note": "Six to eight seconds per resume, in a list view"
                },
                {
                    "id": "screen",
                    "label": "Recruiter and phone screens",
                    "note": "Where the outcome is actually decided"
                }
            ],
            "edges": [
                {
                    "from": "parse",
                    "to": "index"
                },
                {
                    "from": "index",
                    "to": "search"
                },
                {
                    "from": "search",
                    "to": "skim"
                },
                {
                    "from": "skim",
                    "to": "screen"
                }
            ],
            "lit": "parse"
        }
    },
    "ai-tools-developers-2025": {
        "slug": "ai-tools-developers-2025",
        "form": "matrix",
        "title": "One tool per kind of task, not one tool for everything",
        "takeaway": "Copilot for boilerplate, Perplexity for anything current, and Claude or o1/o3 when the problem is genuinely hard.",
        "sources": [
            "The mistake most developers make is using one tool for everything.",
            "Treat Copilot as a fast typist, not a smart architect.",
            "For research and factual questions, Perplexity is often better than any other tool.",
            "Use GPT-4o for everyday coding help, Perplexity for research, and o1/o3 when you have a genuinely hard problem where you need confident accuracy over speed."
        ],
        "data": {
            "x": {
                "low": "Routine",
                "high": "Genuinely hard",
                "name": "How hard the problem is"
            },
            "y": {
                "low": "No",
                "high": "Yes",
                "name": "Needs current information"
            },
            "cells": [
                {
                    "x": "low",
                    "y": "low",
                    "label": "Copilot or Cursor",
                    "note": "Boilerplate and autocomplete: a fast typist"
                },
                {
                    "x": "high",
                    "y": "low",
                    "label": "Claude or ChatGPT o1/o3",
                    "note": "Architecture, review, multi-step debugging"
                },
                {
                    "x": "low",
                    "y": "high",
                    "label": "Perplexity",
                    "note": "Searches the web in real time and cites sources"
                },
                {
                    "x": "high",
                    "y": "high",
                    "label": "Perplexity, then Claude",
                    "note": "Research the current state first, then implement"
                }
            ],
            "lit": "Claude or ChatGPT o1/o3"
        }
    },
    "ats-resume-software-engineer": {
        "slug": "ats-resume-software-engineer",
        "form": "funnel",
        "title": "30 applications, two replies, and no robot said no",
        "takeaway": "You are rarely rejected by a robot; a resume that parses badly or misses the recruiter's search terms is simply never surfaced.",
        "sources": [
            "You heard back from two.",
            "The other 28 never even had a human read your application.",
            "This parsing process is where most resumes fail.",
            "You are rarely rejected by a robot.",
            "The critical insight: your resume must be readable by a machine before a human ever sees it."
        ],
        "data": {
            "stages": [
                {
                    "label": "Submitted",
                    "count": 30,
                    "note": "4 hours of writing, tailored to the job description"
                },
                {
                    "label": "Parsed into structured data",
                    "note": "Columns, tables and graphics confuse the parser"
                },
                {
                    "label": "Surfaced by the recruiter's search",
                    "note": "Missing the exact terms typed means never surfaced"
                },
                {
                    "label": "Heard back",
                    "count": 2,
                    "note": "The other 28 never had a human read them"
                }
            ],
            "lit": "Parsed into structured data"
        }
    },
    "behavioral-interview-questions-software-engineer": {
        "slug": "behavioral-interview-questions-software-engineer",
        "form": "matrix",
        "title": "Disagreement, the most-asked question: two traps, one good shape",
        "takeaway": "A disagreement story scores when evidence settled it and your own position moved at least partly.",
        "sources": [
            "The single most-asked behavioural question in engineering.",
            "Two traps: picking a disagreement where you were obviously right and they were obviously stupid, and picking one where you simply caved.",
            "The good version is a real technical disagreement resolved through evidence, ideally where your position shifted at least partly.",
            "Interviewers are not scoring charisma."
        ],
        "data": {
            "x": {
                "low": "No evidence",
                "high": "Resolved through evidence",
                "name": "How it was settled"
            },
            "y": {
                "low": "Never moved",
                "high": "Shifted at least partly",
                "name": "Your position"
            },
            "cells": [
                {
                    "x": "low",
                    "y": "low",
                    "label": "You were obviously right",
                    "note": "Trap: they were obviously stupid and you held firm"
                },
                {
                    "x": "low",
                    "y": "high",
                    "label": "You simply caved",
                    "note": "Trap: your position moved, but nothing settled it"
                },
                {
                    "x": "high",
                    "y": "low",
                    "label": "Settled by evidence",
                    "note": "The good version, short of the ideal: your position did not shift"
                },
                {
                    "x": "high",
                    "y": "high",
                    "label": "Evidence, and your view shifted",
                    "note": "The good version: evidence, and your position shifted at least partly"
                }
            ],
            "lit": "Evidence, and your view shifted"
        }
    },
    "big-o-notation-explained": {
        "slug": "big-o-notation-explained",
        "form": "bars",
        "title": "One row down the table: twenty million versus a trillion",
        "takeaway": "Big O is about growth: at a million items, moving from O(n log n) to O(n²) is the gap between a blink and not today.",
        "sources": [
            "The row worth internalising is O(n log n) to O(n²).",
            "At a million elements, that is twenty million operations versus a trillion: the difference between \"finishes while you blink\" and \"does not finish today\".",
            "Almost every meaningful optimisation in an interview is moving between two adjacent rows of that table.",
            "Big O notation describes how the work an algorithm does grows as its input grows."
        ],
        "data": {
            "unit": "operations at n = 1,000,000",
            "bars": [
                {
                    "label": "O(1) constant",
                    "value": 1,
                    "note": "From the post's table at n = 1,000,000; hash map lookup"
                },
                {
                    "label": "O(log n) logarithmic",
                    "value": 20,
                    "note": "From the post's table at n = 1,000,000 (~20); binary search"
                },
                {
                    "label": "O(n) linear",
                    "value": 1000000,
                    "note": "From the post's table at n = 1,000,000; one pass over the input"
                },
                {
                    "label": "O(n log n) linearithmic",
                    "value": 20000000,
                    "note": "From the post's table at n = 1,000,000 (~20,000,000); comparison sorting"
                },
                {
                    "label": "O(n²) quadratic",
                    "value": 1000000000000,
                    "note": "From the post's table at n = 1,000,000; nested loop over the same input"
                }
            ],
            "lit": "O(n²) quadratic"
        }
    },
    "campus-placement-preparation-guide": {
        "slug": "campus-placement-preparation-guide",
        "form": "checklist",
        "title": "Prepare for the whole funnel, not just the coding round",
        "takeaway": "Each stage cuts people for a different reason, and the biggest cut, aptitude, is not where students spend their time.",
        "sources": [
            "Students who spend all three months on DSA and none on aptitude regularly get filtered before anyone looks at their code.",
            "This is where interviews are actually lost.",
            "The HR round is not a formality.",
            "They are the ones who prepared for the whole funnel instead of one part of it."
        ],
        "data": {
            "items": [
                {
                    "item": "Clear the CGPA cutoff and backlogs",
                    "ifSkipped": "Below the cutoff, most doors do not open regardless of skills"
                },
                {
                    "item": "Aptitude, two to three hours a week",
                    "ifSkipped": "Filtered before anyone looks at your code"
                },
                {
                    "item": "DSA by pattern, 150 to 200 problems",
                    "ifSkipped": "Being unable to write a clean BFS is fatal"
                },
                {
                    "item": "Core subjects: OS, DBMS, CN, OOP",
                    "ifSkipped": "Unable to explain a deadlock in the technical interview"
                },
                {
                    "item": "Two projects you can defend in depth",
                    "ifSkipped": "Interviewers pick the one you understand least"
                },
                {
                    "item": "Treat the HR round as a real round",
                    "ifSkipped": "It eliminates people every season"
                }
            ]
        }
    },
    "campus-recruiting-what-companies-want": {
        "slug": "campus-recruiting-what-companies-want",
        "form": "checklist",
        "title": "Each round is for something different, so brief for each",
        "takeaway": "Early rounds clear a floor and late rounds test judgement; one tip per round avoids preparing for all of them the same way.",
        "sources": [
            "Early rounds are about clearing a floor, quickly.",
            "Late rounds are about judgement.",
            "Preparing for them the same way wastes time on both.",
            "An interviewer cannot give credit for reasoning they cannot hear."
        ],
        "data": {
            "items": [
                {
                    "item": "Online test: timed aptitude practice",
                    "ifSkipped": "Speed and accuracy decide the floor, not cleverness"
                },
                {
                    "item": "Coding: handle edge cases first",
                    "ifSkipped": "A clever half-solution loses to correct code on an easy problem"
                },
                {
                    "item": "Technical: think out loud",
                    "ifSkipped": "No credit for reasoning the interviewer cannot hear"
                },
                {
                    "item": "Know one project deeply",
                    "ifSkipped": "No answer to why you made the choices you made"
                },
                {
                    "item": "Design: name one trade-off honestly",
                    "ifSkipped": "A diagram of ten boxes is worth less than one trade-off"
                },
                {
                    "item": "HR: four or five real stories",
                    "ifSkipped": "The HR round gets treated as a formality"
                }
            ]
        }
    },
    "coding-interview-patterns": {
        "slug": "coding-interview-patterns",
        "form": "patternMap",
        "title": "Name the pattern from the signal in the question",
        "takeaway": "Each problem is one of about fifteen patterns, and a word in the question tells you which.",
        "sources": [
            "Most coding interview problems are the same fifteen or so problems wearing different clothes.",
            "The word contiguous is the signal.",
            "A useful test: after solving a problem, close it and write down the pattern name and the trigger in one sentence.",
            "Patterns solve exactly one problem: the blank page at minute one of a coding interview."
        ],
        "data": {
            "pairs": [
                {
                    "signal": "sorted array, find a pair",
                    "pattern": "two pointers",
                    "example": "Container With Most Water"
                },
                {
                    "signal": "contiguous subarray, longest or shortest",
                    "pattern": "sliding window",
                    "example": "Minimum Window Substring"
                },
                {
                    "signal": "have I seen this, count, group",
                    "pattern": "hash map",
                    "example": "Group Anagrams"
                },
                {
                    "signal": "a monotonic yes/no answer",
                    "pattern": "binary search",
                    "example": "Koko Eating Bananas"
                },
                {
                    "signal": "every valid arrangement",
                    "pattern": "backtracking",
                    "example": "Subsets"
                },
                {
                    "signal": "how many ways, min or max cost",
                    "pattern": "dynamic programming",
                    "example": "Coin Change"
                }
            ]
        }
    },
    "deploy-your-portfolio-project": {
        "slug": "deploy-your-portfolio-project",
        "form": "flow",
        "title": "From a claim to evidence: the path from repository to live URL",
        "takeaway": "Nobody will clone and run your project; getting it live means getting secrets, config and the database right on the way.",
        "sources": [
            "A portfolio project that is not deployed is a claim.",
            "A deployed one is evidence.",
            "This is the one that actually hurts, and it happens to people who know better.",
            "Deleting the file does not help - it is in the history, and history is public.",
            "An empty app is worse than no app."
        ],
        "data": {
            "nodes": [
                {
                    "id": "repo",
                    "label": "Repository",
                    "note": "A claim nobody will clone and run"
                },
                {
                    "id": "secrets",
                    "label": "Secrets out of the repo",
                    "note": ".env.example committed, .env never"
                },
                {
                    "id": "config",
                    "label": "No hardcoded localhost",
                    "note": "Hosts and URLs come from the environment"
                },
                {
                    "id": "db",
                    "label": "Hosted database, migrated, seeded",
                    "note": "Your local Postgres is not coming with you"
                },
                {
                    "id": "live",
                    "label": "Live URL",
                    "note": "Loads for a stranger, with data in it"
                }
            ],
            "edges": [
                {
                    "from": "repo",
                    "to": "secrets"
                },
                {
                    "from": "secrets",
                    "to": "config"
                },
                {
                    "from": "config",
                    "to": "db"
                },
                {
                    "from": "db",
                    "to": "live",
                    "label": "evidence"
                }
            ],
            "lit": "secrets"
        }
    },
    "dsa-study-plan-coding-interview": {
        "slug": "dsa-study-plan-coding-interview",
        "form": "timeline",
        "title": "Three months, and the last two weeks are interviews, not new problems",
        "takeaway": "Build patterns in months 1 and 2, then shift from studying to performing under a 45-minute timer.",
        "sources": [
            "Data structures and algorithms are not facts to memorize.",
            "Month 3 is not about learning new material.",
            "This is the most important part of the plan.",
            "This plan requires 1-1.5 hours per day, 6 days per week."
        ],
        "data": {
            "unit": "weeks",
            "events": [
                {
                    "at": "Weeks 1-4",
                    "label": "Foundations",
                    "note": "Arrays, hash maps, linked lists, stacks, trees"
                },
                {
                    "at": "Weeks 5-8",
                    "label": "Intermediate patterns",
                    "note": "Binary search, graphs, heaps, DP foundations"
                },
                {
                    "at": "Weeks 9-10",
                    "label": "Advanced topics and weak areas",
                    "note": "Audit months 1 and 2, drill what you struggled with"
                },
                {
                    "at": "Weeks 11-12",
                    "label": "Mock interviews and simulation",
                    "note": "At least 10 full simulations, 45-minute timer, out loud"
                },
                {
                    "at": "Week before",
                    "label": "Review notes, no new material",
                    "note": "1-2 mock interviews per day"
                }
            ],
            "lit": "Weeks 11-12"
        }
    },
    "dynamic-programming-interview-guide": {
        "slug": "dynamic-programming-interview-guide",
        "form": "table",
        "title": "Coin Change to 6: greedy takes three coins, the table finds two",
        "takeaway": "Each cell reuses smaller answers, so dp[6] finds 3 + 3 where greedy's 4 + 1 + 1 cannot.",
        "sources": [
            "What is hard is recognising that a problem is DP at all, and then choosing what the subproblem should be.",
            "Greedy takes the biggest coin that fits, every time: 4, then 1, then 1.",
            "The right answer is 3 + 3.",
            "Write out a small table by hand before you write the loop, every time."
        ],
        "data": {
            "caption": "Coins [1, 3, 4]: dp[i] is the fewest coins that make i, with dp[0] = 0",
            "columns": [
                "i",
                "dp[i]",
                "from"
            ],
            "rows": [
                [
                    "1",
                    "1",
                    "dp[0]+1"
                ],
                [
                    "2",
                    "2",
                    "dp[1]+1"
                ],
                [
                    "3",
                    "1",
                    "dp[0]+1 via 3"
                ],
                [
                    "4",
                    "1",
                    "dp[0]+1 via 4"
                ],
                [
                    "5",
                    "2",
                    "dp[4]+1 via 1"
                ],
                [
                    "6",
                    "2",
                    "dp[3]+1 via 3"
                ]
            ],
            "lit": {
                "row": 5,
                "col": 1
            }
        }
    },
    "full-stack-developer-roadmap": {
        "slug": "full-stack-developer-roadmap",
        "form": "layers",
        "title": "One of each, built up in order, then ship it",
        "takeaway": "One frontend framework, one backend runtime, one database, shipped, beats a little of six stacks.",
        "sources": [
            "One frontend framework.",
            "Ship something with those before adding anything.",
            "Depth in one stack beats familiarity with six, and it is not close.",
            "Skipping this is the most expensive mistake in the entire roadmap.",
            "You are not a full stack developer until something you built is running somewhere other than your laptop."
        ],
        "data": {
            "layers": [
                {
                    "name": "Fundamentals, 6-10 weeks",
                    "items": [
                        "HTML",
                        "CSS before Tailwind",
                        "JavaScript, where the time goes",
                        "Git"
                    ]
                },
                {
                    "name": "Frontend, 8-12 weeks",
                    "items": [
                        "Pick React",
                        "Then TypeScript",
                        "Then Next.js or Remix",
                        "Ignore: Redux for now"
                    ]
                },
                {
                    "name": "Backend, 10-14 weeks",
                    "items": [
                        "Node with Express",
                        "HTTP properly",
                        "REST API design",
                        "Auth, validation, background jobs"
                    ]
                },
                {
                    "name": "Databases, 4-6 weeks",
                    "items": [
                        "Start with PostgreSQL",
                        "Raw SQL, joins, indexes",
                        "Then an ORM",
                        "NoSQL later"
                    ]
                },
                {
                    "name": "Shipping, 4-6 weeks",
                    "items": [
                        "Deploy to one host",
                        "Docker basics only",
                        "CI on every push",
                        "Monitoring"
                    ]
                }
            ]
        }
    },
    "github-profile-software-engineer": {
        "slug": "github-profile-software-engineer",
        "form": "beforeAfter",
        "title": "The same work, made visible in the ten seconds a recruiter gives",
        "takeaway": "The README, the pins and the graph are all a recruiter sees; make those three things say something.",
        "sources": [
            "A technical recruiter who clicks your GitHub gives it about ten seconds.",
            "So the whole optimisation is: make those three things say something.",
            "Almost nobody has one, which is why having a good one is disproportionately effective.",
            "The first pin is the one that gets clicked."
        ],
        "data": {
            "before": {
                "label": "Says nothing",
                "lines": [
                    "No profile README, or a wall of badges",
                    "Good work on page two behind eleven forks",
                    "Pin cards with blank descriptions",
                    "A repository called test"
                ]
            },
            "after": {
                "label": "Says something",
                "lines": [
                    "Three sentences on what you build, then links",
                    "Four to six finished, deployed pins, best first",
                    "Each pin has a description and a live URL",
                    "Practice repos private, old ones archived"
                ]
            },
            "change": [
                "The README says what you build",
                "The first pin has the most interesting hard part",
                "Nothing is deleted, only archived or made private"
            ]
        }
    },
    "hiring-junior-engineers-without-resume-filter": {
        "slug": "hiring-junior-engineers-without-resume-filter",
        "form": "funnel",
        "title": "Screen juniors on what they can do, not on their resume",
        "takeaway": "Replace the resume filter with one short, identical, auto-scored round, then judge projects by the decisions behind them.",
        "sources": [
            "The result is a funnel that looks rigorous and selects for background.",
            "Instead of reading 400 resumes, send every applicant the same short first round:",
            "For the candidates who clear the first round, projects are the best evidence a junior has.",
            "A process that takes a month loses the best of them to the one that takes a week."
        ],
        "data": {
            "stages": [
                {
                    "label": "Every applicant, no resume filter",
                    "count": 400,
                    "note": "the same 20 to 30 minute round, auto-scored"
                },
                {
                    "label": "Cleared the pass mark",
                    "note": "set as a floor, not an ideal"
                },
                {
                    "label": "Project conversation",
                    "note": "ten minutes on decisions, not features"
                },
                {
                    "label": "Offer within a week",
                    "note": "four rounds, same loop for everyone"
                }
            ],
            "lit": "Every applicant, no resume filter"
        }
    },
    "how-to-approach-coding-interview-problems": {
        "slug": "how-to-approach-coding-interview-problems",
        "form": "dialogue",
        "title": "The first five minutes, out loud, before any code",
        "takeaway": "Restate, work an example, state the brute force, name the waste, propose and check: that is the part being scored.",
        "sources": [
            "Steps 1 to 6 take five minutes and are the part being scored.",
            "This is the step people skip, and it is the highest-value one.",
            "This sentence is the hinge of the entire interview.",
            "Every optimisation is the removal of a specific waste, and naming it is what turns \"I remembered the answer\" into \"I derived the answer\"."
        ],
        "data": {
            "turns": [
                {
                    "who": "interviewer",
                    "text": "Given an array of integers and a target, return the indices of the two numbers that add to the target.",
                    "note": "Left underspecified on purpose"
                },
                {
                    "who": "candidate",
                    "text": "So I am given an array of integers and a target, and I need to return the indices of the two numbers that add to the target. Is that right?",
                    "note": "Restating catches a misunderstanding while it is still free"
                },
                {
                    "who": "candidate",
                    "text": "nums = [2, 7, 11, 15], target = 9. 2 + 7 = 9, so indices 0 and 1.",
                    "note": "One example by hand: the step people skip"
                },
                {
                    "who": "candidate",
                    "text": "The brute force is a nested loop over every pair, which is O(n²) time and O(1) space.",
                    "note": "A correct baseline before a clever one"
                },
                {
                    "who": "candidate",
                    "text": "The inner loop searches for target - nums[i] every time. That search is the expensive part.",
                    "note": "Naming the waste: the hinge of the interview"
                },
                {
                    "who": "candidate",
                    "text": "I would store each value and its index in a hash map as I go. That is O(n) time and O(n) space. Does that sound reasonable to start with?",
                    "note": "Propose, then check before writing code"
                }
            ]
        }
    },
    "how-to-become-a-software-engineer": {
        "slug": "how-to-become-a-software-engineer",
        "form": "timeline",
        "title": "12 to 24 months, and the phase people skip is depth",
        "takeaway": "Reaching employable takes 12 to 24 months; depth in months 9 to 14 separates the hired from tutorial finishers.",
        "sources": [
            "The phase people skip is the third one, and it is the one that separates people who get hired from people who have completed a lot of tutorials.",
            "Bootcamp claims of \"job-ready in 12 weeks\" describe when the classroom ends, not when someone pays you.",
            "There is no shortcut, and the people who make it are not the fastest learners - they are the ones still going in month fourteen when it stopped being novel and had not yet started paying."
        ],
        "data": {
            "unit": "months",
            "events": [
                {
                    "at": "1-3",
                    "label": "Fundamentals",
                    "note": "One language, data structures, control flow"
                },
                {
                    "at": "4-8",
                    "label": "Building",
                    "note": "Small projects, then a real one; Git, HTTP, databases"
                },
                {
                    "at": "9-14",
                    "label": "Depth",
                    "note": "One stack properly; testing, debugging, reading code"
                },
                {
                    "at": "15-20",
                    "label": "Job-ready",
                    "note": "Portfolio, open source, interview prep, applications"
                }
            ],
            "lit": "9-14"
        }
    },
    "learning-to-code-with-ai": {
        "slug": "learning-to-code-with-ai",
        "form": "decisionPath",
        "title": "Delegate what you can verify faster than you could write",
        "takeaway": "Hand over the code that is in the way; write the part you are learning yourself, then ask for a critique.",
        "sources": [
            "Learning happens when you retrieve something with effort, not when you recognise it as correct.",
            "Never accept code you could not have written, without first understanding why it works.",
            "For anything you are actively trying to learn, the worse version you wrote is more valuable than the better version you accepted.",
            "Where verification is cheap, delegate freely."
        ],
        "data": {
            "question": "Can you verify the output faster than you could produce it?",
            "branches": [
                {
                    "answer": "Yes",
                    "then": "Boilerplate, regex, explaining code",
                    "verdict": "Delegate freely"
                },
                {
                    "answer": "No",
                    "then": "Checking needs the skill being built",
                    "verdict": "Write it yourself, then ask for critique"
                }
            ]
        }
    },
    "leetcode-alternatives": {
        "slug": "leetcode-alternatives",
        "form": "decisionPath",
        "title": "The platform should follow from the interview format",
        "takeaway": "LeetCode fits the algorithmic screen; a take-home or debugging round needs different practice.",
        "sources": [
            "The platform should follow from the format.",
            "If you skip this step you will spend three months grinding array problems for a company whose entire process is a take-home plus a code walkthrough.",
            "None of that is trainable on a problem site.",
            "The mistake is not using LeetCode."
        ],
        "data": {
            "question": "What interview are you preparing for?",
            "branches": [
                {
                    "answer": "Algorithmic screen, 45 minutes",
                    "then": "LeetCode, NeetCode or Codeforces, by pattern",
                    "verdict": "LeetCode is genuinely good at this"
                },
                {
                    "answer": "Take-home assignment",
                    "then": "Build something small and complete under a four-hour timer",
                    "verdict": "Scoping judgement is not trainable on a problem site"
                },
                {
                    "answer": "Pair programming or debugging round",
                    "then": "Exercism, real open source, Codewars",
                    "verdict": "Reading existing code is a distinct skill"
                }
            ]
        }
    },
    "linkedin-profile-software-engineer": {
        "slug": "linkedin-profile-software-engineer",
        "form": "checklist",
        "title": "A twenty-minute pass: get found, then survive ten seconds",
        "takeaway": "Fix what a recruiter's search and first ten seconds see - headline, About's first lines, skills, location - before any polish.",
        "sources": [
            "Your LinkedIn does one job: get found, and survive the ten seconds after.",
            "Recruiters search by keyword, and your headline is heavily weighted in that search.",
            "A blank or vague location removes you from most searches.",
            "That is most of the available value."
        ],
        "data": {
            "items": [
                {
                    "item": "Headline: title, technologies, goal",
                    "ifSkipped": "Aspiring, enthusiast and passionate match no search anybody runs"
                },
                {
                    "item": "First two lines of About define you",
                    "ifSkipped": "About is cut after about two lines on mobile; the rest goes unread"
                },
                {
                    "item": "Reorder your top three skills",
                    "ifSkipped": "Recruiters filter on the top three, shown prominently"
                },
                {
                    "item": "Set your location",
                    "ifSkipped": "A blank or vague location removes you from most searches"
                },
                {
                    "item": "Pin one project to Featured",
                    "ifSkipped": "You lose the only link somebody will actually click"
                },
                {
                    "item": "Open to work, recruiter-only if employed",
                    "ifSkipped": "Blank titles and locations there mean you do not appear"
                }
            ]
        }
    },
    "mock-interviews-at-scale": {
        "slug": "mock-interviews-at-scale",
        "form": "sum",
        "title": "One structured mock fits in twenty-five minutes",
        "takeaway": "A fixed four-part mock, scored on a short rubric, lets a whole batch be tested on the same things.",
        "sources": [
            "A mock for a final-year engineering student can fit in twenty-five minutes:",
            "A mock is only useful if two students who sat it can compare notes and find they were tested on the same things.",
            "Use four, each scored 1 to 4:",
            "Write the questions down."
        ],
        "data": {
            "unit": "minutes",
            "lines": [
                {
                    "what": "Introduction",
                    "amount": 3,
                    "note": "a clear, short account of who they are"
                },
                {
                    "what": "Project walkthrough",
                    "amount": 8,
                    "note": "explaining a decision, handling a follow-up"
                },
                {
                    "what": "Technical question",
                    "amount": 10,
                    "note": "reasoning out loud on one problem"
                },
                {
                    "what": "Behavioural question",
                    "amount": 4,
                    "note": "a real example, told with structure"
                }
            ],
            "budget": 25
        }
    },
    "mock-technical-interview-guide": {
        "slug": "mock-technical-interview-guide",
        "form": "dialogue",
        "title": "Talking through the maximum subarray instead of going quiet",
        "takeaway": "Interviewers cannot evaluate a candidate who does not talk; restate, clarify, agree the approach, ask when stuck, then trace.",
        "sources": [
            "Most candidates fail communication, not problem-solving.",
            "They go quiet and code.",
            "Do not start coding without buy-in.",
            "Getting a hint does not disqualify you - staying silent for 10 minutes does."
        ],
        "data": {
            "turns": [
                {
                    "who": "candidate",
                    "text": "So to make sure I understand - I need to find the maximum sum subarray. Is that right?",
                    "note": "Restating lets the interviewer correct you early"
                },
                {
                    "who": "candidate",
                    "text": "Can the array be empty? What should I return in that case?",
                    "note": "Clarifying questions earn credit for edge cases"
                },
                {
                    "who": "candidate",
                    "text": "Brute force is O(n²). I think dynamic programming gives O(n) time. Does that approach make sense before I code it?",
                    "note": "State the approach and wait for confirmation"
                },
                {
                    "who": "candidate",
                    "text": "I am a little stuck on this part. Can I talk through what I am thinking?",
                    "note": "Interviewers almost always give hints when asked"
                },
                {
                    "who": "candidate",
                    "text": "Let me trace through with [−2, 1, −3, 4, −1, 2, 1, −5, 4].",
                    "note": "Catching your own bugs beats having them pointed out"
                }
            ]
        }
    },
    "new-grad-software-engineer-jobs": {
        "slug": "new-grad-software-engineer-jobs",
        "form": "funnel",
        "title": "Track the funnel: where it stops tells you what to fix",
        "takeaway": "Silence is not feedback; the stage where your search stalls names the problem, and each stage has a different fix.",
        "sources": [
            "Track the funnel, not the outcome.",
            "If you are getting no replies, the problem is upstream - resume or targeting.",
            "If you get screens and no onsites, it is technical preparation.",
            "Different problems, different fixes, and you cannot tell which without the numbers."
        ],
        "data": {
            "stages": [
                {
                    "label": "Applications sent",
                    "note": "Twenty tailored beat two hundred generic"
                },
                {
                    "label": "Replies",
                    "note": "None? Upstream: resume or targeting"
                },
                {
                    "label": "Screens",
                    "note": "Screens but no onsites: technical preparation"
                },
                {
                    "label": "Onsites",
                    "note": "Onsites but no offers: usually behavioural or communication"
                },
                {
                    "label": "Offers"
                }
            ],
            "lit": "Replies"
        }
    },
    "open-source-contribution-beginners": {
        "slug": "open-source-contribution-beginners",
        "form": "flow",
        "title": "The first PR is won or lost at picking the project",
        "takeaway": "Pick an active, mid-sized project with a good first issue, then keep the change small enough to review.",
        "sources": [
            "The main reason developers fail to make their first contribution is choosing the wrong project.",
            "Not reading this is the fastest way to get your PR closed immediately.",
            "Scope creep is the single most common reason PRs get rejected or stall.",
            "For now: find one project, fix one thing, open one PR."
        ],
        "data": {
            "nodes": [
                {
                    "id": "pick",
                    "label": "Pick an active, not massive project",
                    "note": "10-200 contributors, a good first issue label"
                },
                {
                    "id": "read",
                    "label": "Read CONTRIBUTING.md",
                    "note": "Skipping it gets a PR closed fastest"
                },
                {
                    "id": "change",
                    "label": "Make the smallest possible change",
                    "note": "No refactoring, no unrelated improvements"
                },
                {
                    "id": "pr",
                    "label": "Open the PR linked to the issue",
                    "note": "Closes #482 links the PR and closes the issue on merge"
                },
                {
                    "id": "review",
                    "label": "Respond to every review comment",
                    "note": "Requested changes are collaboration, not rejection"
                }
            ],
            "edges": [
                {
                    "from": "pick",
                    "to": "read"
                },
                {
                    "from": "read",
                    "to": "change"
                },
                {
                    "from": "change",
                    "to": "pr"
                },
                {
                    "from": "pr",
                    "to": "review"
                }
            ],
            "lit": "pick"
        }
    },
    "open-source-for-your-resume": {
        "slug": "open-source-for-your-resume",
        "form": "beforeAfter",
        "title": "Merged, numbered and specific, or it does not count",
        "takeaway": "An open source entry is worth listing only when a reader who clicks the link finds merged work and a named failure.",
        "sources": [
            "A merged pull request is one of the few claims on a resume that a hiring manager can verify in thirty seconds.",
            "Only list merged work.",
            "It is a link, it is verifiable, and including it signals you expect to be checked.",
            "Not \"fixed a bug\" - the specific failure."
        ],
        "data": {
            "before": {
                "label": "An unmerged, vague claim",
                "lines": [
                    "Contributed to open source",
                    "Fixed a bug",
                    "(an unmerged or still-open PR behind it)"
                ]
            },
            "after": {
                "label": "A merged, checkable entry",
                "lines": [
                    "<project> (12k stars) - merged PR #4821",
                    "Fixed a race condition in cache",
                    "invalidation that returned stale reads",
                    "under concurrent writes; added a",
                    "regression test that reproduced it."
                ]
            },
            "change": [
                "Only merged work is listed",
                "The PR number makes it verifiable",
                "The specific failure, not \"fixed a bug\""
            ]
        }
    },
    "pass-marks-technical-assessments": {
        "slug": "pass-marks-technical-assessments",
        "form": "table",
        "note": "The post has only two pass-mark numbers (70 and 60), too few for 3 bars in one unit.",
        "title": "A pass mark marks the floor, not the score of a good candidate",
        "takeaway": "Anchor the number to the job or to people already doing it, or start at a moderate default and check it after the first cohort.",
        "sources": [
            "It marks the floor.",
            "Someone picks 70% because it sounds reasonable, and from then on it silently decides who you never meet.",
            "It is slow, but it anchors the number to the job instead of to a feeling.",
            "Your pass mark should sit comfortably below the score of people you would hire again."
        ],
        "data": {
            "caption": "Three ways to set a pass mark",
            "columns": [
                "Method",
                "The number comes from",
                "Trade-off"
            ],
            "rows": [
                [
                    "Expert judgement (Angoff)",
                    "Sum of odds a minimally competent pass",
                    "Slow, but anchored to the job"
                ],
                [
                    "Benchmark current engineers",
                    "Comfortably below people you'd rehire",
                    "Needs a group already in the role"
                ],
                [
                    "Platform default",
                    "Start at 60, revisit after a cohort",
                    "Check it once 30 or more have sat it"
                ]
            ],
            "lit": {
                "row": 0,
                "col": 1
            }
        }
    },
    "placement-readiness-metrics": {
        "slug": "placement-readiness-metrics",
        "form": "matrix",
        "title": "Measure readiness, not activity, and report it by department",
        "takeaway": "Track a few signals recruiters screen on and show department numbers outside the cell, never activity or a ranked list.",
        "sources": [
            "Activity counts reward students who are good at looking busy, and a report with thirty columns gets read once.",
            "Login times, time spent on a page and keystrokes measure compliance, not readiness.",
            "Faculty and heads of department need department and section numbers, not a ranked list of names.",
            "A student who trusts the measurement uses it to decide what to work on."
        ],
        "data": {
            "x": {
                "low": "Activity",
                "high": "Readiness signals",
                "name": "What is tracked"
            },
            "y": {
                "low": "Named students",
                "high": "Department numbers",
                "name": "What leaves the cell"
            },
            "cells": [
                {
                    "x": "high",
                    "y": "high",
                    "label": "Department and section numbers",
                    "note": "the movement between runs is what heads of department see"
                },
                {
                    "x": "high",
                    "y": "low",
                    "label": "A ranked list of names",
                    "note": "students experience it as monitoring, and game it"
                },
                {
                    "x": "low",
                    "y": "high",
                    "label": "Hours logged, videos watched",
                    "note": "rewards students who are good at looking busy"
                },
                {
                    "x": "low",
                    "y": "low",
                    "label": "Login times and keystrokes",
                    "note": "measures compliance, not readiness"
                }
            ],
            "lit": "Department and section numbers"
        }
    },
    "placement-season-plan": {
        "slug": "placement-season-plan",
        "form": "timeline",
        "title": "Run the season forward: measure first, drives last",
        "takeaway": "Move the work to the months where it still changes the outcome, so the drives themselves are only logistics.",
        "sources": [
            "You cannot plan for a batch you have not measured.",
            "By then the calendar has already decided the outcome.",
            "Mock interviews do the most good before the season, not during it.",
            "The months below assume a season that opens around the start of the final year."
        ],
        "data": {
            "unit": "months",
            "events": [
                {
                    "at": "Month 1",
                    "label": "Readiness baseline",
                    "note": "one identical hour for every student, shared with heads of department"
                },
                {
                    "at": "Month 2",
                    "label": "Resume clinics, projects",
                    "note": "one written standard; chase students with no project"
                },
                {
                    "at": "Month 3",
                    "label": "Mock interviews, first pass",
                    "note": "structured, same questions for the whole batch"
                },
                {
                    "at": "Month 4",
                    "label": "Outreach with evidence",
                    "note": "a one-page profile per department"
                },
                {
                    "at": "Months 5-6",
                    "label": "Drive logistics",
                    "note": "eligibility lists, one calendar, tested labs"
                },
                {
                    "at": "After",
                    "label": "One page per department",
                    "note": "next year's plan starts from it"
                }
            ],
            "lit": "Month 1"
        }
    },
    "portfolio-project-ideas-software-engineer": {
        "slug": "portfolio-project-ideas-software-engineer",
        "form": "matrix",
        "title": "Worth building means it forces a decision and gets finished",
        "takeaway": "A to-do app forces no decisions and an abandoned hard project reads as not finishing; only the finished, decision-forcing one counts.",
        "sources": [
            "A portfolio project is worth building when it forces a decision you can be interviewed about.",
            "Three complete, deployed projects beat twelve half-built ones every time.",
            "If it is not live, it does not count - a repository is a claim, and a running deployment is evidence.",
            "The reason projects die is scope, not difficulty."
        ],
        "data": {
            "x": {
                "low": "Forces no decision",
                "high": "Forces a decision",
                "name": "The hard part"
            },
            "y": {
                "low": "Abandoned",
                "high": "Finished and deployed",
                "name": "Finished"
            },
            "cells": [
                {
                    "x": "low",
                    "y": "low",
                    "label": "A to-do app, left in a repo",
                    "note": "Nothing to ask about and nothing to see"
                },
                {
                    "x": "low",
                    "y": "high",
                    "label": "A deployed weather dashboard",
                    "note": "Fine as learning, worthless as a portfolio piece"
                },
                {
                    "x": "high",
                    "y": "low",
                    "label": "Commits stop in week two",
                    "note": "Reads as evidence you do not finish things"
                },
                {
                    "x": "high",
                    "y": "high",
                    "label": "URL shortener with click counts",
                    "note": "Smallest version that keeps the hard part, live"
                }
            ],
            "lit": "URL shortener with click counts"
        }
    },
    "project-based-learning-cs": {
        "slug": "project-based-learning-cs",
        "form": "beforeAfter",
        "title": "The same coursework project, assigned for the interview it will face",
        "takeaway": "Scope, checkpoints and a rubric weighted to decisions and the viva turn a mini project into something a student can defend.",
        "sources": [
            "The difference between a project that helps in placements and one that does not is almost entirely in how it is assigned and assessed.",
            "A project brief of \"build an e-commerce platform\" produces a folder of half-finished pages and a student who cannot explain any of them.",
            "The decision log is the most valuable artefact in the list.",
            "Most of the marks sit in the decision log and the viva, which are the parts that cannot be copied."
        ],
        "data": {
            "before": {
                "label": "Assigned for output",
                "lines": [
                    "Brief: build an e-commerce platform",
                    "One end-of-semester deadline",
                    "Marks for features and interface polish",
                    "Result: half-finished pages, no story"
                ]
            },
            "after": {
                "label": "Assigned for the interview",
                "lines": [
                    "One core feature with a real constraint",
                    "Proposal, core, hardening, decision log, viva",
                    "Decisions 30%, viva 30% of the marks",
                    "Result: a working link and a decision log"
                ]
            },
            "change": [
                "Scope shrinks to what can be finished and deployed",
                "Checkpoints replace one panicked week",
                "Marks move to the parts that cannot be copied"
            ]
        }
    },
    "questions-to-ask-interviewer-software-engineer": {
        "slug": "questions-to-ask-interviewer-software-engineer",
        "form": "checklist",
        "title": "The last five minutes are scored, and they are your due diligence",
        "takeaway": "Bring two or three questions per interviewer about how the work really runs, and let the answers change your decision.",
        "sources": [
            "That is a scored moment, and it scores badly.",
            "Not because it is rude, but because it tells the interviewer you are evaluating nothing.",
            "The single highest-information question in this list.",
            "Vagueness here is the most reliable red flag in the whole interview."
        ],
        "data": {
            "items": [
                {
                    "item": "Ask two or three questions",
                    "ifSkipped": "Saying no tells the interviewer you are evaluating nothing"
                },
                {
                    "item": "Ask: one-line change to production?",
                    "ifSkipped": "You miss CI, test suite health, review culture and release process in one answer"
                },
                {
                    "item": "Ask about on-call, every time",
                    "ifSkipped": "You miss the most reliable red flag in the interview: vagueness"
                },
                {
                    "item": "Ask: success in six months?",
                    "ifSkipped": "An undefined role can turn into something different from what you interviewed for"
                },
                {
                    "item": "Match the question to the person",
                    "ifSkipped": "Asking the wrong person is itself a small negative signal"
                },
                {
                    "item": "Leave compensation to the recruiter",
                    "ifSkipped": "It consumes time you could spend learning about the work"
                }
            ]
        }
    },
    "software-engineer-career-path": {
        "slug": "software-engineer-career-path",
        "form": "ladder",
        "title": "Levels track scope of ownership, not years",
        "takeaway": "Each rung is a bigger problem with more ambiguity absorbed, and you do the next rung's work before you get its title.",
        "sources": [
            "Levels are about scope of ownership.",
            "Promotion to senior does not come from doing mid-level work faster or more elegantly.",
            "You operate at the next level first. Then you get the title.",
            "Levels track scope, not tenure."
        ],
        "data": {
            "rungs": [
                {
                    "level": "L1 Intern / Junior",
                    "does": "A task: you get told what to do",
                    "signal": "Finishes things, asks for help in time"
                },
                {
                    "level": "L2 Software Engineer",
                    "does": "A feature: you fill in the details",
                    "signal": "Ships a feature without being tracked"
                },
                {
                    "level": "L3 Senior Engineer",
                    "does": "A project: you define the plan",
                    "signal": "Vague problem in, a plan in a week"
                },
                {
                    "level": "L4 Staff Engineer",
                    "does": "Multiple teams: you find the problem",
                    "signal": "Impact across teams, not more code"
                },
                {
                    "level": "L5 Principal",
                    "does": "An organisation: what problems matter",
                    "signal": "Decides what problems matter"
                }
            ]
        }
    },
    "software-engineer-cover-letter": {
        "slug": "software-engineer-cover-letter",
        "form": "annotated",
        "title": "Four short paragraphs that say what the resume cannot",
        "takeaway": "Hook, one proof with a number, the gap named plainly, a short close: specific, honest, and every claim checkable.",
        "sources": [
            "A cover letter is only worth writing when it can say something the resume structurally cannot.",
            "Under 250 words total.",
            "Under 200 words.",
            "Specific, honest about the gap, and every claim is checkable."
        ],
        "data": {
            "kind": "text",
            "heading": "New graduate letter, under 200 words",
            "lines": [
                "Hi [Name],",
                "I have been using [Product] since my second year of university,",
                "and the thing that made me apply was the changelog entry about rebuilding the diff view.",
                "The most relevant thing I have built is a self-hosted analytics tool that ingests and aggregates about two million events a day.",
                "I have not worked full-time as an engineer yet. What I do have is eleven merged pull requests to [open source project].",
                "Happy to talk any time. Code and resume attached."
            ],
            "notes": [
                {
                    "line": 2,
                    "note": "The hook: why this company, concretely, and unfakeable at scale"
                },
                {
                    "line": 3,
                    "note": "Proof: one relevant thing built, with a number"
                },
                {
                    "line": 4,
                    "note": "The gap named in one sentence, then the mitigation"
                },
                {
                    "line": 5,
                    "note": "The close: short, no begging"
                }
            ]
        }
    },
    "software-engineer-resume-bullet-points": {
        "slug": "software-engineer-resume-bullet-points",
        "form": "beforeAfter",
        "title": "From what you were responsible for to what changed",
        "takeaway": "Action verb, what you built, how, and a measurable outcome: a bullet an interviewer can ask about is one that does work.",
        "sources": [
            "Action verb + what you built + how + measurable outcome.",
            "Nobody was ever hired for being responsible for something.",
            "The first contains none of them and cannot be asked about at all.",
            "A bullet nobody can ask a question about is a bullet that does no work."
        ],
        "data": {
            "before": {
                "label": "Before",
                "lines": [
                    "Responsible for improving database performance"
                ]
            },
            "after": {
                "label": "After",
                "lines": [
                    "Cut p95 API latency from 380ms to 210ms",
                    "by adding composite indexes and a Redis cache-aside layer",
                    "for the three hottest endpoints"
                ]
            },
            "change": [
                "A verb that says what you did: Cut",
                "Real numbers: 380ms to 210ms",
                "Named technologies: indexes and Redis",
                "Enough shape for a follow-up question"
            ]
        }
    },
    "software-engineering-portfolio-guide": {
        "slug": "software-engineering-portfolio-guide",
        "form": "annotated",
        "title": "A project README that reads as an engineer, not a tutorial-follower",
        "takeaway": "Anyone can list a stack; the live link, the architecture decisions and what you learned are what a recruiter reads as proof of work.",
        "sources": [
            "The mental model is simple: your portfolio is a proof-of-work system.",
            "The architecture decisions section is what separates a junior portfolio from a mid-level one.",
            "Anyone can list a stack.",
            "A project that cannot be seen running is not a portfolio, it is homework."
        ],
        "data": {
            "kind": "code",
            "heading": "README.md, condensed from the post's skeleton",
            "lines": [
                "# Splitwise-for-Trips",
                "Splits shared holiday expenses in the fewest possible transfers.",
                "Live demo | API docs",
                "## Stack",
                "## Architecture decisions",
                "Chose Postgres over MongoDB: a genuinely relational shape.",
                "## Run it locally",
                "## What I learned",
                "The naive settlement algorithm was unusably slow above nine people."
            ],
            "notes": [
                {
                    "line": 1,
                    "note": "What it does: one sentence, no jargon"
                },
                {
                    "line": 2,
                    "note": "If it is not live, it does not count"
                },
                {
                    "line": 5,
                    "note": "A trade-off you made, with the alternative named"
                },
                {
                    "line": 8,
                    "note": "One you got wrong signals intellectual honesty"
                }
            ]
        }
    },
    "star-method-interview-software-engineers": {
        "slug": "star-method-interview-software-engineers",
        "form": "annotated",
        "title": "Most of a STAR answer is Action, and it never stops before the Result",
        "takeaway": "Keep context to a few seconds, spend 60% on what you did and why, and always land a result with numbers.",
        "sources": [
            "Almost every weak answer gets this ratio wrong in the same direction: two minutes of context, twenty seconds of what they actually did, and no result at all.",
            "Say \"I\", not \"we\".",
            "The single most common failure in behavioural answers is an answer that just stops."
        ],
        "data": {
            "kind": "text",
            "heading": "The billing-job story, part by part",
            "lines": [
                "S: Second engineer on a four-person billing team.",
                "S: A quarter of invoices were arriving late.",
                "T: I owned the fix end to end. Two weeks, no downtime.",
                "A: I added timing instrumentation around each stage.",
                "A: 80% of runtime was one N+1 query over 40,000 invoices.",
                "A: I rewrote it as one batched join: 26 minutes to about 90 seconds.",
                "A: Behind a feature flag, both paths ran for two nights.",
                "R: Late invoices went from about 25% to zero.",
                "R: I wrote up the N+1 pattern and two other jobs got fixed."
            ],
            "notes": [
                {
                    "line": 0,
                    "note": "Situation: be boring and be fast. About 10% of the answer."
                },
                {
                    "line": 2,
                    "note": "Task: makes your scope unambiguous, and the constraints show the difficulty."
                },
                {
                    "line": 4,
                    "note": "Action gets 60%: say I, not we, with specific decisions and trade-offs."
                },
                {
                    "line": 7,
                    "note": "Result: never skip it. Numbers where you have them, then impact beyond the task."
                }
            ]
        }
    },
    "structured-interviews-engineering-hiring": {
        "slug": "structured-interviews-engineering-hiring",
        "form": "annotated",
        "title": "Same question, same rubric, scores written before anyone talks",
        "takeaway": "When every candidate answers the same question against the same anchors, the scores measure the candidates, not the conversations.",
        "sources": [
            "When the questions differ, the scores measure the conversations.",
            "Score each answer on a small scale, 1 to 4 works well because it removes the easy middle.",
            "Collect every interviewer's scores before anyone speaks.",
            "Structure constrains what you ask and how you judge, not how you behave."
        ],
        "data": {
            "kind": "text",
            "heading": "One past-behaviour question, scored",
            "lines": [
                "Q: Tell me about a time you had to ship with a known bug.",
                "What did you decide and why?",
                "Fixed follow-up: What would you do differently?",
                "Strong: names the trade-off, gives the reason, checked the outcome",
                "Acceptable: a reasonable decision, but not the reasoning",
                "Weak: no concrete example, or blames others",
                "Score 1 to 4, recorded before the debrief"
            ],
            "notes": [
                {
                    "line": 0,
                    "note": "The same question for every candidate for the role, in the same order"
                },
                {
                    "line": 2,
                    "note": "Follow-ups are allowed but fixed too"
                },
                {
                    "line": 3,
                    "note": "Anchors written before any interview, in observable terms"
                },
                {
                    "line": 6,
                    "note": "Independent scores; 1 to 4 removes the easy middle"
                }
            ]
        }
    },
    "system-design-interview-prep": {
        "slug": "system-design-interview-prep",
        "form": "timeline",
        "title": "Fundamentals first, then most of the time on practice",
        "takeaway": "Reading is not practising; six weeks build the concepts and the final six are repetition and feedback out loud.",
        "sources": [
            "The most common mistake developers make is reading about system design without practicing it.",
            "Build the fundamentals first.",
            "The final phase is the most important: repetition and feedback.",
            "System design cannot be crammed."
        ],
        "data": {
            "unit": "weeks",
            "events": [
                {
                    "at": "1-2",
                    "label": "Foundational concepts",
                    "note": "Scaling, load balancing, caching, databases"
                },
                {
                    "at": "3-4",
                    "label": "Core design patterns",
                    "note": "Rate limiter, URL shortener, news feed, notifications"
                },
                {
                    "at": "5-6",
                    "label": "Deep dives",
                    "note": "Databases, caching, queues, consistency"
                },
                {
                    "at": "7-12",
                    "label": "Practice problems and mocks",
                    "note": "45 minutes alone per problem, then explain it out loud"
                }
            ],
            "lit": "7-12"
        }
    },
    "technical-interview-process-design": {
        "slug": "technical-interview-process-design",
        "form": "flow",
        "title": "Design the loop from the job, one round per need, then stop",
        "takeaway": "A loop built from what the job needs, with a written rubric and gate per round, fits in four rounds and a week.",
        "sources": [
            "Most engineering interview loops were not designed.",
            "This guide is a way to design the loop on purpose: decide what the job needs, pick one round per need, give each round a pass mark, and stop.",
            "Every round in your loop should map to exactly one of these.",
            "Rubrics written after the interview describe the candidate you liked."
        ],
        "data": {
            "nodes": [
                {
                    "id": "job",
                    "label": "List what the job needs",
                    "note": "four or five things done in the first six months"
                },
                {
                    "id": "rounds",
                    "label": "Pick one round per need",
                    "note": "maps to none: delete it; two to one need: keep the better"
                },
                {
                    "id": "rubric",
                    "label": "Write the rubric first",
                    "note": "strong, acceptable and weak, in observable terms"
                },
                {
                    "id": "gate",
                    "label": "Set pass mark and gate",
                    "note": "hard gate or advisory, decided up front"
                },
                {
                    "id": "stop",
                    "label": "Stop at four rounds",
                    "note": "a loop that runs in a week, the same for everyone"
                }
            ],
            "edges": [
                {
                    "from": "job",
                    "to": "rounds"
                },
                {
                    "from": "rounds",
                    "to": "rubric"
                },
                {
                    "from": "rubric",
                    "to": "gate"
                },
                {
                    "from": "gate",
                    "to": "stop"
                }
            ],
            "lit": "job"
        }
    },
    "technical-phone-screen-guide": {
        "slug": "technical-phone-screen-guide",
        "form": "sum",
        "title": "A 45-minute screen leaves twenty-five minutes to code",
        "takeaway": "The compression is the difficulty: clarify fast, narrate the whole time, and test before you say done.",
        "sources": [
            "It is usually 45 minutes, usually one problem, usually with someone who has your resume open and four other screens booked that day.",
            "Twenty-five minutes of coding is not long, and it is why the first five minutes matter disproportionately: five minutes spent clarifying is fine, five minutes spent silently reading is a quarter of your coding time gone.",
            "So the rule for this round specifically is: narrate more than feels natural."
        ],
        "data": {
            "unit": "minutes",
            "budget": 45,
            "lines": [
                {
                    "what": "Introductions and background",
                    "amount": 5
                },
                {
                    "what": "Problem given, you ask questions",
                    "amount": 5,
                    "note": "Clarifying is fine; silent reading eats coding time"
                },
                {
                    "what": "You solve it, talking",
                    "amount": 25,
                    "note": "Narrate every decision and every long pause"
                },
                {
                    "what": "Complexity, edge cases, follow-up",
                    "amount": 5
                },
                {
                    "what": "Your questions for them",
                    "amount": 5,
                    "note": "Have two, about the work"
                }
            ]
        }
    },
    "work-sample-vs-take-home-assignment": {
        "slug": "work-sample-vs-take-home-assignment",
        "form": "decisionPath",
        "title": "Pick per role: a timed work sample, or a capped take-home",
        "takeaway": "Most roles are best served by a short work sample; a take-home earns its cost only when independent structure is the job.",
        "sources": [
            "Screening at volume, or junior roles: work sample, timed, auto-checked where possible.",
            "Senior roles where independent structure is the job: a short, capped take-home plus a conversation about it.",
            "Never both as hard gates in the same loop.",
            "They filter for free time, not skill."
        ],
        "data": {
            "question": "What does this role need you to see?",
            "branches": [
                {
                    "answer": "Screening at volume, or a junior role",
                    "then": "Same task and scoring, under an hour",
                    "verdict": "Timed work sample"
                },
                {
                    "answer": "Senior, independent structure is the job",
                    "then": "Capped scope, rubric, paid past 2 hours",
                    "verdict": "Capped take-home plus a talk"
                },
                {
                    "answer": "Tempted to use both",
                    "then": "Never both as hard gates in one loop",
                    "verdict": "Choose one gate"
                }
            ]
        }
    },
}
