'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import {
    Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle
} from '@repo/ui/components/ui/sheet'
import { Input } from '@repo/ui/components/ui/input'
import { Button } from '@repo/ui/components/ui/button'
import {
    Sparkles, Target
} from 'lucide-react'
import { createSubGoal } from '@/actions/(main)/pathfinder/subgoals.action'
import { awaitBackgroundJob } from '@/hooks/use-background-job'
import toast from '@repo/ui/components/ui/sonner'
import type { GoalUsageSummary } from '@/app/store/pathfinderStore'
import { usePathfinderStore } from '@/app/store/pathfinderStore'
import { PATHFINDER_CREDITS } from '@/lib/constants/pricing'
import { InlineLoader } from "@repo/ui/components/ui/inline-loader"

interface CreateSubGoalSheetProps {
    open: boolean
    onOpenChange: (open: boolean) => void
    goalId: string
    onSuccess: (subGoal: {
        id: string
        title: string
        description: string | null
        status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'SKIPPED'
        source: string
        aiCodingProblem: unknown
        hasCoding: boolean
        quizCompleted: boolean
        quizScore: number | null
        codingCompleted: boolean
        codingPassed: boolean
        order: number
        studioId?: string | null
    }, _aiResources?: unknown, usageSummary?: GoalUsageSummary) => void
}

export function CreateSubGoalSheet({
    open,
    onOpenChange,
    goalId,
    onSuccess,
}: CreateSubGoalSheetProps) {
    const [title, setTitle] = useState('')
    const [isLoading, setIsLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const setGoalUsage = usePathfinderStore((s) => s.setGoalUsage)
    const router = useRouter()

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault()
        if (!title.trim() || isLoading) return

        setIsLoading(true)
        setError(null)

        try {
            const result = await createSubGoal({
                goalId,
                title: title.trim(),
                source: 'text',
            })

            if (!result.success) {
                const err = result as { code?: string; pendingCredits?: number }
                if (err.code === 'USAGE_BLOCKED') {
                    setError(
                        `AI usage limit reached (${err.pendingCredits ?? 0} credits pending). ` +
                        `Add credits to continue. Threshold: ${PATHFINDER_CREDITS.usageBlockThreshold} credits.`
                    )
                } else {
                    setError(result.error ?? 'Failed to create sub-goal')
                }
                return
            }

            if (result.subGoal) {
                if (result.usageSummary) {
                    setGoalUsage(goalId, result.usageSummary)
                }
                onSuccess(
                    result.subGoal as Parameters<typeof onSuccess>[0],
                    undefined,
                    result.usageSummary
                )
                setTitle('')
                onOpenChange(false)

                // The sub-goal row and its Studio already exist - the sheet closes
                // on them, not on the AI. The explanation and practice problems are
                // generated by the `subgoal_generation` worker job (PF-W2), so this
                // follows that job and refreshes the page when it lands.
                //
                // Deliberately AFTER the sheet closes and without blocking it: the
                // user has a usable sub-goal either way, and making them watch a
                // spinner for content that appears on its own is the behaviour this
                // migration exists to remove.
                if (result.jobId) {
                    toast.success('Sub-goal created. Generating your explanation and practice problems…')
                    void awaitBackgroundJob(result.jobId).then((outcome) => {
                        if (outcome.ok) {
                            toast.success('Your sub-goal content is ready')
                            router.refresh()
                        } else {
                            // The sub-goal is still there and still usable, so this
                            // reports what is missing rather than what failed.
                            toast.error(`${outcome.error} Your sub-goal was saved - open it to add content yourself.`)
                        }
                    })
                } else if (result.generationError) {
                    toast.error(`${result.generationError} Your sub-goal was saved without generated content.`)
                }
            }
        } catch (err) {
            console.error('Error creating sub-goal:', err)
            setError('Something went wrong. Please try again.')
        } finally {
            setIsLoading(false)
        }
    }

    const handleOpenChange = (next: boolean) => {
        if (!isLoading) {
            setError(null)
            if (!next) setTitle('')
            onOpenChange(next)
        }
    }

    return (
        <Sheet open={open} onOpenChange={handleOpenChange}>
            <SheetContent side="right" className="w-full sm:max-w-md">
                <SheetHeader>
                    <SheetTitle className="flex items-center gap-2">
                        <Target className="w-5 h-5 text-neutral-900 dark:text-neutral-100" />
                        Add Learning Task
                    </SheetTitle>
                    <SheetDescription>
                        What do you want to learn today? We&apos;ll generate resources, videos, docs, and practice content.
                        It costs about 1 to 2 credits per sub-goal. Your usage is shown at the top right.
                    </SheetDescription>
                </SheetHeader>
                <form onSubmit={handleSubmit} className="mt-6 space-y-4">
                    <div>
                        <label className="text-sm font-medium text-neutral-700 dark:text-neutral-300">
                            Topic
                        </label>
                        <Input
                            value={title}
                            onChange={(e) => setTitle(e.target.value)}
                            placeholder="e.g. React Hooks, Array methods, REST APIs"
                            className="mt-1.5"
                            disabled={isLoading}
                            autoFocus
                        />
                    </div>

                    {
                        error && (
                            <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
                        )
                    }

                    {
                        !isLoading ? (
                            <Button
                                type="submit"
                                className="w-full bg-neutral-800 hover:bg-neutral-700"
                                disabled={!title.trim()}
                            >
                                Generate Content
                            </Button>
                        ) : (
                            <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 p-8 text-center">
                                <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-neutral-100 dark:bg-neutral-800/30 flex items-center justify-center">
                                    <InlineLoader size="lg" className="text-neutral-900 dark:text-neutral-100" />
                                </div>
                                <h3 className="font-semibold text-neutral-900 dark:text-white mb-1">
                                    Generating Content
                                </h3>
                                <p className="text-sm text-neutral-500 dark:text-neutral-400 mb-2 flex items-center justify-center gap-2">
                                    <Sparkles className="w-4 h-4 text-neutral-900 dark:text-neutral-100" />
                                    Finding videos and docs, then writing the content
                                </p>
                                <p className="text-xs text-neutral-600 dark:text-neutral-400">
                                    This usually takes 5-10 seconds
                                </p>
                            </div>
                        )
                    }
                </form>
            </SheetContent>
        </Sheet>
    )
}