/**
 * Checks every blog post story against its post, then writes content/post-stories.ts (plan/web/story ST-14).
 *
 *   node scripts/post-stories.mjs           check only: prints each problem, exits 1 if any
 *   node scripts/post-stories.mjs --write   check, then regenerate content/post-stories.ts
 *
 * A story lives in content/post-stories/<slug>.json. The checks: every source sentence appears
 * verbatim in content/posts/<slug>.md (markdown stripped); every number in the drawing appears in
 * the post; no em or en dashes; the spec's length limits; and no two posts in one category share a
 * form. The generated .ts types each story as PostStory, so `tsc` also checks the shape.
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..")
const DIR = path.join(ROOT, "content/post-stories")
const POSTS = path.join(ROOT, "content/posts")
const OUT = path.join(ROOT, "content/post-stories.ts")

const blogTs = fs.readFileSync(path.join(ROOT, "content/blog.ts"), "utf8")
// BLOG_POSTS is keyed by slug: '<slug>': { title, ..., category: '<category>', ... }
const category = Object.fromEntries([...blogTs.matchAll(/\n\s+'([a-z0-9-]+)': \{[\s\S]*?category: '([^']+)'/g)].map((m) => [m[1], m[2]]))

const plain = (md) => md
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/\*\*|__|`/g, "")
    .replace(/(^|\s)_([^_]+)_/g, "$1$2")
    .replace(/\s+/g, " ")
const strings = (v) => (typeof v === "string" ? [v] : Array.isArray(v) ? v.flatMap(strings) : v && typeof v === "object" ? Object.values(v).flatMap(strings) : [])
// Positions, not facts: a note's line index and a lit cell's row and column are not checked.
const POSITIONAL = new Set(["line", "row", "col"])
const numbers = (v) => (typeof v === "number" ? [v] : Array.isArray(v) ? v.flatMap(numbers) : v && typeof v === "object" ? Object.entries(v).flatMap(([k, x]) => (POSITIONAL.has(k) ? [] : numbers(x))) : [])
const ONES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen"]
const TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"]
/** A number as a post may write it in words, up to ninety-nine ("twenty-five"). */
const inWords = (n) => (!Number.isInteger(n) || n < 0 || n > 99 ? null : n < 20 ? ONES[n] : TENS[Math.floor(n / 10)] + (n % 10 ? "-" + ONES[n % 10] : ""))

const problems = []
const stories = []
const files = fs.readdirSync(DIR).filter((f) => f.endsWith(".json")).sort()
for (const f of files) {
    const slug = f.replace(/\.json$/, "")
    const s = JSON.parse(fs.readFileSync(path.join(DIR, f), "utf8"))
    const say = (m) => problems.push(`${slug}: ${m}`)
    if (s.slug !== slug) say(`slug field is "${s.slug}"`)
    const mdPath = path.join(POSTS, `${slug}.md`)
    if (!fs.existsSync(mdPath)) { say("no post markdown"); continue }
    const text = plain(fs.readFileSync(mdPath, "utf8"))
    const digits = text.replace(/,(?=\d{3})/g, "")
    if (!Array.isArray(s.sources) || s.sources.length < 2) say("fewer than 2 sources")
    for (const src of s.sources ?? []) if (!text.includes(src.replace(/\s+/g, " "))) say(`source not in post: "${src.slice(0, 70)}"`)
    for (const n of numbers(s.data)) {
        const forms = [String(n), n.toLocaleString("en-US"), n.toLocaleString("en-IN")]
        const word = inWords(n)
        if (!forms.some((x) => digits.includes(x.replace(/,/g, "")) || text.includes(x)) && !(word && new RegExp(`\\b${word}\\b`, "i").test(text))) say(`number ${n} not in post`)
    }
    for (const t of strings(s)) if (/[\u2013\u2014]/.test(t)) say(`dash in "${t.slice(0, 50)}"`)
    if ((s.title ?? "").length > 70) say("title over 70")
    if ((s.takeaway ?? "").length > 140) say("takeaway over 140")
    if (!category[slug]) say("not in content/blog.ts")
    stories.push(s)
}

// No two posts in one category share a form.
const seen = {}
for (const s of stories) {
    const k = `${category[s.slug]}|${s.form}`
    if (seen[k]) problems.push(`${s.slug}: shares "${s.form}" with ${seen[k]} in ${category[s.slug]}`)
    else seen[k] = s.slug
}
const missing = Object.keys(category).filter((slug) => !files.includes(`${slug}.json`))
for (const m of missing) problems.push(`${m}: no story`)

console.log(`${stories.length} stories, ${problems.length} problems`)
for (const p of problems) console.log("  " + p)

if (process.argv.includes("--write") && problems.length === 0) {
    const body = stories.map((s) => `    ${JSON.stringify(s.slug)}: ${JSON.stringify(s, null, 4).replace(/\n/g, "\n    ")},`).join("\n")
    fs.writeFileSync(OUT, `// Generated by scripts/post-stories.mjs from content/post-stories/*.json. Edit those, then run it with --write.
import type { PostStory } from "@/components/blog/story/types"

export const POST_STORIES: Record<string, PostStory> = {
${body}
}
`)
    console.log(`wrote ${path.relative(ROOT, OUT)}`)
}
process.exit(problems.length ? 1 : 0)
