"use server"

import { getSession } from "@repo/auth"
import { headers } from "next/headers"
import { db, pathfinderGoals } from "@repo/db"
import { revalidatePath } from "next/cache"
import { startBackgroundJob } from "@/actions/(main)/workers/jobs.action"
import { scrapeJobDescription } from "@/utils/jobs/extract-job-description"
import { generateAndCheckSlug } from "./goals.action"
import { matchReportedLoop } from "@/lib/interview-reports/match"

/**
 * Create a Pathfinder goal from a job description.
 *
 * The entry point the standalone Job Interview Assistant owned, rebuilt on
 * Pathfinder - see `plan/interview-prep/`. Everything AFTER this function is
 * existing Pathfinder machinery: the questions are sub-goals, the answers are
 * quiz attempts, the coding is a coding submission, and publishing or pricing
 * the result uses the same `pathfinderGoals` columns every other goal uses.
 *
 * The goal is inserted SYNCHRONOUSLY and the questions are generated by a job.
 * That split is deliberate and matches `createPathfinderGoal`: the user gets a
 * real goal and a URL immediately, and a generation failure leaves something
 * usable rather than nothing.
 */

export interface CreateInterviewPrepInput {
    /** The role. Becomes the goal title. */
    position: string
    /** Pasted description. Takes precedence over `jobUrl` when both are given. */
    jobDescription?: string
    /** Scraped when `jobDescription` is absent. */
    jobUrl?: string
    companyUrl?: string
    counts?: { technical?: number; behavioral?: number; coding?: number }
    isPublic?: boolean
}

const DEFAULT_COUNTS = { technical: 8, behavioral: 8, coding: 3 }

/**
 * Shortest posting we will generate from.
 *
 * A scrape that clears the login-wall guard can still be a stub. Generating 19
 * questions from two sentences produces generic filler and charges for it.
 */
const MIN_DESCRIPTION_CHARS = 200

export async function createInterviewPrepGoal(input: CreateInterviewPrepInput) {
    try {
        const session = await getSession(await headers())
        if (!session?.user?.id) {
            return { success: false as const, error: "Unauthorized" }
        }
        const userId = session.user.id

        const position = input.position?.trim()
        if (!position) {
            return { success: false as const, error: "Which role is this for?" }
        }

        // Resolve the description BEFORE anything is written or charged.
        let description = input.jobDescription?.trim() ?? ""
        let scrapedTitle = ""

        if (!description) {
            const url = input.jobUrl?.trim()
            if (!url) {
                // Neither given. A validation error, not an LLM call.
                return {
                    success: false as const,
                    error: "Paste the job description, or give a link to the posting.",
                }
            }
            // The same scraper and the same login-wall guard the cover letter
            // uses. LinkedIn, Glassdoor and Indeed all serve a sign-in page to
            // anything without a session, and that page is not a job description.
            const scraped = await scrapeJobDescription(url)
            if (!scraped.success) {
                return { success: false as const, error: scraped.error }
            }
            description = scraped.description
            scrapedTitle = scraped.title
        }

        if (description.length < MIN_DESCRIPTION_CHARS) {
            return {
                success: false as const,
                error: `That is only ${description.length} characters, which is too short to generate a useful interview from. Paste the full posting.`,
            }
        }

        const counts = { ...DEFAULT_COUNTS, ...(input.counts ?? {}) }
        const total = counts.technical + counts.behavioral + counts.coding
        if (total < 1) {
            return { success: false as const, error: "Ask for at least one question." }
        }

        const title = `Interview prep: ${position}`
        const slug = await generateAndCheckSlug(title, userId)

        const [goal] = await db
            .insert(pathfinderGoals)
            .values({
                userId,
                title,
                slug,
                category: "INTERVIEW_PREP",
                // Interview questions are not graded by difficulty tier the way a
                // study plan is; the role carries that. INTERMEDIATE is the
                // neutral default rather than a claim about the candidate.
                level: "INTERMEDIATE",
                focusAreas: [],
                overview: `Interview questions generated from the ${position} posting.`,
                // Provenance. Without these the description that produced the
                // questions is gone the moment generation finishes.
                sourceJobDescription: description,
                sourceCompanyUrl: input.companyUrl?.trim() || null,
                sourceCompanyInfo: scrapedTitle ? { scrapedTitle } : null,
                // Private by default. A goal built from someone's job hunt is not
                // something to publish without being asked.
                isPublic: input.isPublic ?? false,
            })
            .returning()

        if (!goal) {
            return { success: false as const, error: "Could not create that goal" }
        }

        // Credits are HELD here and settled or refunded when the app sees a
        // terminal status. The worker never touches credits.
        //
        // 1 credit per 2 questions, the rate the Job Interview Assistant charged.
        // Recorded as a decision in plan/interview-prep/overview.md, including the
        // fact that Pathfinder's other generation jobs are currently free.
        // Reported questions first when the company and role have a loop (CMP-2e).
        const reported = await matchReportedLoop({ position, companyUrl: input.companyUrl, scrapedTitle }).catch((e: unknown) => {
            console.error("matchReportedLoop:", e instanceof Error ? e.message : e)
            return null
        })
        const started = await startBackgroundJob(
            "interview_prep_generation",
            { goalId: goal.id, counts, ...(reported ? { reported } : {}) },
            { cost: Math.ceil(total / 2), reason: `Interview prep: ${position}` },
        )

        revalidatePath("/pathfinder")

        // A failed DISPATCH is not a failed goal. The goal exists, is reachable at
        // its slug, and can be retried - same contract as `createPathfinderGoal`.
        return {
            success: true as const,
            goalId: goal.id,
            slug: goal.slug,
            jobId: started.success ? started.jobId : undefined,
            jobError: started.success ? undefined : started.error,
        }
    } catch (error: unknown) {
        console.error("Error creating interview prep goal:", error)
        return {
            success: false as const,
            error: error instanceof Error ? error.message : "Something went wrong",
        }
    }
}
